[build]
    base = "/carwrapping"
    publish = "../.next"
    command = "npm run build"


[[plugins]]
    package = "@netlify/plugin-nextjs"

[[plugins]]
    package = "netlify-plugin-inline-functions-env"
    [plugins.inputs]
        buildEvent = "onBuild"
        
[[redirects]]
    from = "/*"
    to = "/"
    status = 200